name: qwq
on:
  push:
  issues:

jobs:
  worker:
    runs-on: windows-latest
#    strategy:
#      matrix:
#        base: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#        next: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: working
      run: |
        curl -o ocr-lib.zip https://${{ secrets.REMOTE }}/ocr-lib.zip
        Expand-Archive -Path ".\ocr-lib.zip" -DestinationPath ".\ocr"
        cd ".\ocr\"
        ".\Cheese.Ocr4399.exe"


        curl -o generator.jar https://${{ secrets.REMOTE }}/generator.jar
        java -jar generator.jar

